[window]
  padding = { x = 10, y = 10 }
  dimensions = { columns = 180, lines = 45 }
  opacity = 0.8
  blur = true
[font]
  size = 12
[font.normal]
  family = "JetBrainsMono Nerd Font Mono"
  style = "Regular"